### ISSUE TITLE
웹 기능 구현

### ISSUE THREAD

**Issue by oognuyh** [oognuyh/gguldanji#18]
#### TODO
- [ ] Implement admin features
- [ ] Implement apartment complex features
- [ ] Implement apartment complex talk features
- [ ] Implement transaction history features
- [ ] Implement account features
- [ ] Implement news features
- [ ] Implement notice features
- [ ] Implement bookmark features
