### ISSUE TITLE
단위 테스트

### ISSUE THREAD

**Issue by oognuyh** [oognuyh/gguldanji#19]
#### TODO
- [ ] Add unit tests for admin features
- [ ] Add unit tests for apartment complex features
- [ ] Add unit tests for apartment complex talk features
- [ ] Add unit tests for transaction history features
- [ ] Add unit tests for account features
- [ ] Add unit tests for news features
- [ ] Add unit tests for notice features
- [ ] Add unit tests for bookmark features
